#服务器编码
server:
  tomcat:
    uri-encoding: UTF-8

#将服务注册到注册中心
eureka:
  client:
    service-url:
    defaultZone:  http://localhost:9000/eureka/
  instance:
    preferIpAddress:  true
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}
    statusPageUrlPath:  ${server.context-path:${SERVER_CONTEXTPATH:}}${management.context-path:${MANAGEMENT_CONTEXTPATH:}}${endpoints.info.path:/manager/login/loginIn}
    healthCheckUrlPath: ${server.context-path:${SERVER_CONTEXTPATH:}}${management.context-path:${MANAGEMENT_CONTEXTPATH:}}${endpoints.health.path:/health}
    lease-expiration-duration-in-seconds: 10
    leaseRenewalIntervalInSeconds:  5

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connection-timeout: 60000
    max-idle: 10
    max-active: 2
    max-wait: 60000
    min-idle: 2
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: false
    test-on-borrow: true
    test-on-return: false
    initial-size: 20
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    druid:
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    database-platform:  org.hibernate.dialect.MySQL5Dialect
    database: MySQL
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss
    time-zone:  GMT+8
  servlet:
    multipart:
        max-file-size:  1MB
        max-request-size: 10MB

swagger:
  enable: true
